### ISSUE TITLE
Error - Default CRAN repository not saved (R v4)

### ISSUE THREAD

**Issue by orion434** [EvolEcolGroup/EEG_Docker#12]
Previously (i.e. before testint R v.4), I had those instructions for installing devtools and updating R packages:
From the `dockerfile`:
```
RUN \
  sudo Rscript -e 'install.packages("devtools")' ; \
  sudo Rscript -e 'update.packages(ask = FALSE")'
```
However, now, rebuilding the docker from a vanilla Ubuntu version with R v4, the default `repos` is set to `@CRAN@` and a critical error is thrown:

```
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
```

The default repo can be changed with:
```
sudo Rscript -e 'r = getOption("repos"); r["CRAN"] = "http://cran.us.r-project.org" ; options(repos = r)'
```
but settings are not saved in different instances of the console (i.e. every new line is a new instance).

I currently solved it by explicitly writing down a mirror 
```
RUN \
  sudo Rscript -e 'install.packages("devtools",repos = "http://cran.us.r-project.org")' ; \
  sudo Rscript -e 'update.packages(ask = FALSE,repos = "http://cran.us.r-project.org")'
```

but the same instructions need to be changed also in the yml file when checking and updating the docker. It can be solved by writing explicitly the mirror but it would be better if a default repo can be set once and for all when building the image.

@dramanica Do you know any other way to set it permanently, other than [create and edit a .Rprofile file](https://www.r-bloggers.com/permanently-setting-the-cran-repository/) (it will need to be all edited via command line, feasible but not straightforward).

**Comment by dramanica** [comment]
One option is to set the R_LIBS_SITE environmental variable. See:
https://stackoverflow.com/questions/24387660/how-to-change-libpaths-permanently-in-r

**Comment by orion434** [comment]
It is not about the local library folder, but the `repos` option for retrieving them.
In any case, I explicitly set in the `repos` equal to `https://cloud.r-project.org/` (automatic select the best mirror) both in the dockerfile and yml file. Now we have a working docker an CI.
I leave this issue open in case you have further suggestions, otherwise you can close it.

**Comment by dramanica** [comment]
Sorry, I misread it. There isn't any way I know of, except for using a start up file.
