### ISSUE TITLE
Add doxygen and valgrind to docker

### ISSUE THREAD

**Issue by dramanica** [EvolEcolGroup/EEG_Docker#5]
We have a new test that is only run if `doxygen` is available, and I plan to create one using `valgrind`. Both have to be installed via `apt-get`. It might be worth having a quick chat so that I become a bit more familiar with how the docker creation and maintenance works.

**Comment by orion434** [comment]
The packages that create the Docker are in the Dockerfile:
https://github.com/EvolEcolGroup/EEG_Docker/blob/master/Dockerfile

The docker should be rebuilt on the 1st of the month, manually, or after a commit (see config.yml file).

In rcisgem the config.yml is also installing `qpdf` `pandoc` and `pandoc-citeproc`. Shall I add those as well to the docker?

**Comment by dramanica** [comment]
Very clear, thank you. Yes, please, could you add the `rcisgem` additional packages, as well as `doxygen` and `valgrind`? Thanks!

**Comment by orion434** [comment]
Done in PR https://github.com/EvolEcolGroup/EEG_Docker/pull/6

**Comment by dramanica** [comment]
Sorry, I just realised that doxygen also requires graphviz! Apologies.

**Comment by dramanica** [comment]
For the moment I have added an `apt-get graphviz` in the circle ci yml for `cisgem` but it woudl be nice to eventually have it directly in the Docker.

**Comment by dramanica** [comment]
Implemented in PR #7.

**Comment by orion434** [comment]
Merged with PR https://github.com/EvolEcolGroup/EEG_Docker/pull/7

Unless additional packages are required, this issue can now be closed
