### ISSUE TITLE
Create a new branch/docker with R version 4

### ISSUE THREAD

**Issue by orion434** [EvolEcolGroup/EEG_Docker#9]
The docker should be updated with R version 4.0 (currently 4.0.2)

- [x] Before implementing this important change a new branch and docker should be created to implement the installation of R and all the required R packages. 
- [x] Once the docker is created, the CI tests should pass to verify that `rcisgem` is able to run with no errors.
- [x] Lastly, the branch could be merged via PR into the main branch

If needed, a similar process could be repeated for the `mt_dna_combine` docker and repository.

[Cran instruction on installing R v.4.0 on Ubuntu](https://cran.r-project.org/bin/linux/ubuntu/)

**Comment by orion434** [comment]
The docker was initially based on Rocker's [R-Ubuntu Docker](https://hub.docker.com/r/rocker/r-ubuntu) that still use R version 3.4.0. Indeed, the current dockerfile did not install R or Ubuntu, but just call the existing EEG docker and check/update the listed apt an packages.

The options are to either update R version and R packages or recreate a complete Dockerfile from a clean Ubuntu, then install R 4.0 and all the other apt and R packages. As baseline, it should be possible to use the existing [Dockerfile for Rocker R-Ubuntu Docker](https://hub.docker.com/r/rocker/r-ubuntu/dockerfile).

**Comment by dramanica** [comment]
Somethign doesn't add up. The Docker currently as version 3.6.3 (I can see it from the CI output). Also, looking at the R-Ubuntu Docker webpage, there is an `r-base` version 4.0.2.

**Comment by orion434** [comment]
On https://github.com/rstudio/r-docker , there are available base images with different os version and R version based on parameters: `rstudio/r-base:x.y.z-distro`, including Ubuntu 18.04, 20.04 and R 4.0.2.
In comparison, the rocker's tidyverse docker are based on debian (while rocker/r-ubuntu:18.04 should not have yet R v 4.0.2).

**Comment by orion434** [comment]
@dramanica, if you have time, can you please check if the failure of the devtools check is caused by packages to be updated, so to exclude other internal causes/bugs/misconfiguration:

```
W  checking re-building of vignette outputs (1m 42.3s)
   Error(s) in re-building vignettes:
   --- re-building ‘cisgem_contributor_guide.Rmd’ using rmarkdown
   --- finished re-building ‘cisgem_contributor_guide.Rmd’
   
   --- re-building ‘cisgem_user_guide.Rmd’ using markdown

...
❯ checking re-building of vignette outputs ... WARNING
  Error(s) in re-building vignettes:
  --- re-building ‘cisgem_contributor_guide.Rmd’ using rmarkdown
  --- finished re-building ‘cisgem_contributor_guide.Rmd’
  
  --- re-building ‘cisgem_user_guide.Rmd’ using rmarkdown
```

https://app.circleci.com/pipelines/github/EvolEcolGroup/rcisgem/478/workflows/5d55c29e-34f7-4767-8fdd-de880416b377/jobs/556

**Comment by dramanica** [comment]
@orion434 I am confused. Where is this failure? The current tests are all working, is it still relevant?

**Comment by orion434** [comment]
Apologied, I do not why, but I mixed an older failing report with the lastest passing one on in the rcisgem repo.
Before doing the merge of this branch I would like to double check some logs and setting in the files but likely it could be merged before next hackaton.

**Comment by dramanica** [comment]
Ok, just let me know when you are ready.

**Comment by orion434** [comment]
I was thinking that might be useful to create and upload on docker.com a separate image with r version 3. Usually, the image is tagged as `latest` and overwrite the previous one. My plan is to have a `r-v3` tagged image as long-term test for a different configuration and the updated one as `latest` (and maybe also `r-v4` as extra tag). In addition I could add a tag or a note for the distro we are using Ubuntu 18.04 LTS (I guess that we will have the 20.04 LTS sometime in the future).

**Comment by orion434** [comment]
Added description and a short readme to the eeg-docker and docker.com repository.
Sketched additional tags for current and future docker including info on ubuntu and r version (e.g. `ubuntu18.04-r3.6` and `ubuntu18.04r4.0`). Future updates are as easy as updating the Dockerfile line `FROM rstudio/r-base:3.6-bionic` with the r version and ubuntu codename. The update procedure is in the readme.

The old `latest` image is about 2.3 Gb with 500-600 layers, while new ones will have ~780Mb and ~22 layers.

Updated image with Ubuntu 18.04 and R 3.6. tagged as `ubuntu18.04r3.6` Created as branch, then merged into `master` (without the tag `latest`).
New release of the repo, tagged [eeg_v1.1_ubuntu18.04r3.6](
https://github.com/EvolEcolGroup/EEG_Docker/releases/tag/eeg_v1.1_ubuntu18.04r3.6)

New image with Ubuntu 18.04 and R 4.0. tagged as `ubuntu18.04r4.0` and `latest`. Created as branch, then merged into `master`.
New release of the repo, tagged [eeg_v1.1_ubuntu18.04r4.0](
https://github.com/EvolEcolGroup/EEG_Docker/releases/tag/eeg_v1.1_ubuntu18.04r4.0)

**Comment by orion434** [comment]
Everything should work properly. Before closing this issue I will wait for some new commit in `rcisgem` so to check that they use correctly the update `latest` image
